function RaportPomiarowS6 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  RAPORTPOMIAROWS6 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  RAPORTPOMIAROWS6 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  RAPORTPOMIAROWS6 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  RaportPomiarowS6 = importfile("P:\git\Ekonometria\Wod20\Raport_Pomiarow.xls", "2019", [6, 348]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Apr-2020 21:25:00

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [6, 348];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 116);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":DL" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Lp", "Data", "Godz", "Prbka", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "Temperatura", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "Odczyn", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "Mtno", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "Barwa", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "Amoniak", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "elazo", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "Azotyny", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51", "Twardo", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "Chlorki", "VarName59", "VarName60", "VarName61", "VarName62", "VarName63", "Indeksnadmanganianowy", "VarName65", "VarName66", "VarName67", "VarName68", "VarName69", "Azotany", "VarName71", "VarName72", "VarName73", "VarName74", "VarName75", "Zapach", "VarName77", "VarName78", "VarName79", "VarName80", "Smak", "VarName82", "VarName83", "VarName84", "VarName85", "Glin", "VarName87", "VarName88", "VarName89", "VarName90", "VarName91", "Przewodnowaciwaelektryczna", "VarName93", "VarName94", "VarName95", "VarName96", "VarName97", "Dwutlenekchloru", "VarName99", "VarName100", "VarName101", "VarName102", "VarName103", "Chlorwolny", "VarName105", "VarName106", "VarName107", "VarName108", "VarName109", "Manganniskizakres", "VarName111", "VarName112", "VarName113", "VarName114", "VarName115", "Operator"];
opts.VariableTypes = ["double", "string", "double", "string", "categorical", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "string", "categorical", "string", "string", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "string", "categorical", "categorical", "string"];

% Specify file level properties
opts.ImportErrorRule = "omitvar";
opts.MissingRule = "omitvar";

% Specify variable properties
opts = setvaropts(opts, ["Data", "Prbka", "VarName6", "VarName55", "VarName61", "VarName67", "VarName97", "VarName99", "VarName100", "VarName101", "VarName113", "Operator"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Data", "Prbka", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "Temperatura", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "Odczyn", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "Mtno", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "Barwa", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "Amoniak", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "elazo", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "Azotyny", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51", "Twardo", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "Chlorki", "VarName59", "VarName60", "VarName61", "VarName62", "VarName63", "Indeksnadmanganianowy", "VarName65", "VarName66", "VarName67", "VarName68", "VarName69", "Azotany", "VarName71", "VarName72", "VarName73", "VarName74", "VarName75", "Zapach", "VarName77", "VarName78", "VarName79", "VarName80", "Smak", "VarName82", "VarName83", "VarName84", "VarName85", "Glin", "VarName87", "VarName88", "VarName89", "VarName90", "VarName91", "Przewodnowaciwaelektryczna", "VarName93", "VarName94", "VarName95", "VarName96", "VarName97", "Dwutlenekchloru", "VarName99", "VarName100", "VarName101", "VarName102", "VarName103", "Chlorwolny", "VarName105", "VarName106", "VarName107", "VarName108", "VarName109", "Manganniskizakres", "VarName111", "VarName112", "VarName113", "VarName114", "VarName115", "Operator"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Lp", "Godz"], "TreatAsMissing", '');

% Import the data
RaportPomiarowS6 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":DL" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    RaportPomiarowS6 = [RaportPomiarowS6; tb]; %#ok<AGROW>
end

end