function RaportPomiarowS6 = importfile2(workbookFile, sheetName, dataLines)
%IMPORTFILE2 Import data from a spreadsheet
%  RAPORTPOMIAROWS6 = IMPORTFILE2(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  RAPORTPOMIAROWS6 = IMPORTFILE2(FILE, SHEET) reads from the specified
%  worksheet.
%
%  RAPORTPOMIAROWS6 = IMPORTFILE2(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  RaportPomiarowS6 = importfile2("P:\git\Ekonometria\Wod20\Raport_Pomiarow.xls", "2019", [6, 348]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Apr-2020 12:11:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [6, 348];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":I" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "Kodprbki", "Miejscepoboru", "Datapoboru", "Godzinapoboru", "Prbobiorca", "Wynik"];
opts.VariableTypes = ["double", "string", "string", "string", "categorical", "string", "categorical", "categorical", "double"];

% % Specify file level properties
% opts.ImportErrorRule = "omitrow";
% opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "VarName3", "Kodprbki", "Datapoboru"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName2", "VarName3", "Kodprbki", "Miejscepoboru", "Datapoboru", "Godzinapoboru", "Prbobiorca"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["VarName1", "Wynik"], "TreatAsMissing", '');

% Import the data
RaportPomiarowS6 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":I" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    RaportPomiarowS6 = [RaportPomiarowS6; tb]; %#ok<AGROW>
end

end